### ISSUE TITLE
What version of ffmpeg is needed to build

### ISSUE THREAD

**Issue by joolzg** [cmassiot/upipe#185]
I just tried to compiler against my own ffmpeg build.

Add to add --disable-shared 1st

Now when linking i get missing members in AVFrame
type
get_buffer
release_buffer

**Comment by cmassiot** [comment]
We are currently using ffmpeg 2.8.X. I think FFmpeg 3.0 doesn't work for the moment, Kieran has an experimental patch for it in his git repository, but it has not been merged yet.
